// 50 fake pre-class submissions for SEE Vibecoding.
// All buildPlan and startupPitch values are hand-written so /api/admin/load-test-data
// is instant and doesn't spam the API. Realistic distribution:
//   Stage: 8 Skeptic / 14 Curious / 18 Tinkering / 10 Building
//   Discipline: 18 Entrepreneurship / 8 Strategy / 7 Marketing / 6 Finance / 6 Ops-Tech / 5 Other

module.exports = [
  // ─── Skeptics (8) ─────────────────────────────────────────────────────────
  {
    stage: 'Skeptic', discipline: 'Entrepreneurship',
    teach: "Use AI to draft a discussion prompt then rewrite it in your own voice",
    wish: "Tell me when student work is genuinely original, not just pattern-matched",
    question: "How do I assess actual learning when AI can do most assignments better than novices?",
    build_idea: "A simple checker that flags when my rubric contradicts itself",
    comfort_food: "Strong espresso and dark chocolate",
    buildPlan: { line1: "A one-page rubric tension finder", line2: "Your current rubric plus two anchor papers", line3: "It names a contradiction you'd already half-noticed" },
    startupPitch: { name: "Bittermind", tagline: "The espresso-pulled productivity stack.", pitch: "AI-curated dark chocolate pairings calibrated to your cortisol curve. We're the only TAM-defining player in the morning-bitterness vertical, with an unfair moat in cocoa percentage data." },
  },
  {
    stage: 'Skeptic', discipline: 'Strategy / Management',
    teach: "Ask AI for three counter-arguments to your strategy case before class",
    wish: "Honestly tell me when my case analysis is shallow",
    question: "Is the speed gain from AI making me a worse thinker over time?",
    build_idea: "A devil's-advocate tool that pushes back on my own analysis",
    comfort_food: "Buttered toast",
    buildPlan: { line1: "A devil's-advocate prompt template for case prep", line2: "Your current case-method teaching note", line3: "It surfaces three objections you didn't plan for" },
    startupPitch: { name: "Crustco", tagline: "Toast, but venture-backed.", pitch: "AI-optimized bread firmness using sensor-laden butter knives. TAM is everyone who's ever made toast. Series A coming once we figure out unit economics on jam." },
  },
  {
    stage: 'Skeptic', discipline: 'Finance / Accounting',
    teach: "Have AI explain a confusing balance sheet to you in plain English first",
    wish: "Catch the moment a student copy-pastes my finance question into ChatGPT",
    question: "How do I teach financial intuition if AI does the calculation for them?",
    build_idea: "A self-graded worked-problem set my students can't AI-shortcut",
    comfort_food: "Bowl of cereal at 10pm",
    buildPlan: { line1: "A handwritten-step worked-problem template", line2: "One of your favorite finance puzzles plus a scratch-work format", line3: "Students who only paste the answer can't pass it" },
    startupPitch: { name: "NocturnOat", tagline: "Cereal for the post-rational hours.", pitch: "AI-personalized 10pm bowls calibrated to your unprocessed regrets. The dairy-disrupting moat is real; the milk-to-flake ratio is our Series A pitch." },
  },
  {
    stage: 'Skeptic', discipline: 'Marketing',
    teach: "Use AI as a brainstorming sparring partner, not a copy generator",
    wish: "Push back when my marketing brief is actually just buzzwords",
    question: "Will AI-generated marketing examples make students worse at noticing real human insight?",
    build_idea: "A bullshit-detector for student campaign briefs",
    comfort_food: "Cold leftover pizza",
    buildPlan: { line1: "A jargon-detector for student campaign briefs", line2: "Three example briefs and your list of empty phrases", line3: "It flags the lines that say nothing" },
    startupPitch: { name: "Slabd", tagline: "Cold pizza, vertically integrated.", pitch: "AI predicts which slice you'll regret most at 3am and pre-stages it in your fridge. TAM is anyone with shame and a Wednesday night." },
  },
  {
    stage: 'Skeptic', discipline: 'Operations / Tech',
    teach: "Ask AI to walk through the failure modes of any system you teach about",
    wish: "Tell me what AI is genuinely bad at, not just what it wants me to think",
    question: "What's a use case where AI is clearly worse than a beginner human?",
    build_idea: "A failure-mode generator for any process I teach",
    comfort_food: "Ramen with an egg",
    buildPlan: { line1: "A failure-mode generator for process diagrams", line2: "One of your operations diagrams plus three real outage stories", line3: "It names a failure mode you don't currently cover" },
    startupPitch: { name: "Yolkflow", tagline: "Ramen as a Service.", pitch: "AI optimizes egg-drop timing using webcam vision and your circadian data. Our defensible moat is the broth-fermentation graph database. Pre-seed open." },
  },
  {
    stage: 'Skeptic', discipline: 'Entrepreneurship',
    teach: "Have AI play your pitch judge before you actually pitch",
    wish: "Tell me when a student's startup idea is already done — and by whom",
    question: "Are we accelerating undergrads into AI-shaped business ideas that aren't theirs?",
    build_idea: "A 'this already exists' detector for student startup pitches",
    comfort_food: "Mom's mac and cheese",
    buildPlan: { line1: "A prior-art finder for student pitches", line2: "Your latest five pitch decks plus three competitor sites", line3: "It names the company that beat them to it" },
    startupPitch: { name: "Béchamels", tagline: "Mom-grade nostalgia, enterprise-priced.", pitch: "Mac and cheese tuned by AI to the exact emotional state of your 14-year-old self. We own the cheddar-anxiety vertical and the moat smells incredible." },
  },
  {
    stage: 'Skeptic', discipline: 'Other',
    teach: "Try writing your worst version first, then ask AI what's missing",
    wish: "Actually tell me what I don't know I don't know about my own field",
    question: "How do I keep my expertise sharp when AI lowers the floor for everyone?",
    build_idea: "A 'what would a grad student spot' critic for my drafts",
    comfort_food: "Plain rice with soy sauce",
    buildPlan: { line1: "A graduate-student critic for your own drafts", line2: "One draft chapter and your discipline's main critiques", line3: "It catches the one thing peer review would catch" },
    startupPitch: { name: "Soyseed", tagline: "Plain rice, but make it a platform.", pitch: "AI-paired soy sauce subscription matching your minimalism aesthetic. We're disrupting umami; our defensible moat is the fermentation calendar." },
  },
  {
    stage: 'Skeptic', discipline: 'Strategy / Management',
    teach: "Read AI's strategy answer, then ask it what it missed",
    wish: "Stop sounding smart when it's actually wrong",
    question: "How do I teach skepticism of AI without sounding like I hate the tool?",
    build_idea: "A confidence-vs-correctness scorer for AI strategy outputs",
    comfort_food: "Plain potato chips",
    buildPlan: { line1: "A confidence-vs-correctness scorer for AI answers", line2: "Five strategy questions where AI confidently flubs", line3: "Students see the pattern in under five minutes" },
    startupPitch: { name: "Saltchain", tagline: "Plain chips, decentralized.", pitch: "AI predicts the crunch profile you need based on quarterly board fatigue. Crisp-as-a-service is venture-scale; the sodium moat is unfair." },
  },

  // ─── Curious (14) ─────────────────────────────────────────────────────────
  {
    stage: 'Curious', discipline: 'Entrepreneurship',
    teach: "Paste your syllabus into Claude and ask what assignment is doing the least work",
    wish: "Sit in on my office hours and remember what each student is wrestling with",
    question: "What's one AI move that genuinely changed how you teach?",
    build_idea: "An office-hours memory that surfaces last week's open threads",
    comfort_food: "Grilled cheese with tomato soup",
    buildPlan: { line1: "An office-hours memory log", line2: "Last week's notes plus your student roster", line3: "It surfaces three threads you forgot were open" },
    startupPitch: { name: "Meltlytics", tagline: "Cheese pulls as a service.", pitch: "AI-tuned grilled cheese with tomato soup pairings, adjusted live for your seasonal sadness index. Cheddar-to-stress unit economics define a category we'd already own." },
  },
  {
    stage: 'Curious', discipline: 'Marketing',
    teach: "Ask AI to summarize your last 5 lectures and tell you what you're missing",
    wish: "Generate ten brand-voice samples I can use as anchor examples",
    question: "How do I teach 'taste' when AI can mimic any voice?",
    build_idea: "A brand-voice anchor generator for case discussion",
    comfort_food: "Ben & Jerry's straight from the pint",
    buildPlan: { line1: "A brand-voice anchor library", line2: "Three brands you teach plus their last ten posts", line3: "Students can spot voice drift in under a minute" },
    startupPitch: { name: "PintLogic", tagline: "Ice cream KPIs, in real time.", pitch: "AI scoops your portfolio of grief flavors. Direct-to-spoon supply chain. The TAM is everyone who has ever owned a freezer; the moat is brain-freeze velocity." },
  },
  {
    stage: 'Curious', discipline: 'Entrepreneurship',
    teach: "Have AI interview you about what you actually mean in your draft",
    wish: "Notice when my course materials drift from my stated learning goals",
    question: "Where should AI be invisible vs visible in my classroom?",
    build_idea: "A drift-detector that compares my syllabus to my actual lectures",
    comfort_food: "Pad thai delivery",
    buildPlan: { line1: "A syllabus-vs-lectures drift detector", line2: "Your syllabus PDF plus three lecture transcripts", line3: "It names the week you went off-script" },
    startupPitch: { name: "Padlock", tagline: "Pad thai but defensible.", pitch: "AI rebalances peanut-to-tamarind ratios based on your imposter-syndrome quarterly trends. Our moat is the noodle gravity model. Series A bowl drops Tuesday." },
  },
  {
    stage: 'Curious', discipline: 'Strategy / Management',
    teach: "Use AI to red-team your case before you teach it",
    wish: "Tell me which case my students will actually remember in five years",
    question: "How do I tell which AI use makes my students sharper vs lazier?",
    build_idea: "A case-stickiness predictor based on past student reflections",
    comfort_food: "Pho on a rainy day",
    buildPlan: { line1: "A case-stickiness predictor", line2: "Five past cases plus end-of-term reflections", line3: "It names the one they'll remember in five years" },
    startupPitch: { name: "Brothware", tagline: "Pho-driven decisioning.", pitch: "AI matches your rainy-day broth to the exact level of weekly executive fatigue. The aromatic moat is fragrant; investors are slurping it up." },
  },
  {
    stage: 'Curious', discipline: 'Finance / Accounting',
    teach: "Ask AI to translate your balance sheet feedback into a student-friendly version",
    wish: "Suggest a real-company analogue for every concept I teach",
    question: "Is there a way to test financial reasoning that's actually AI-resistant?",
    build_idea: "A real-company analogue generator for textbook concepts",
    comfort_food: "Mac & cheese from a box",
    buildPlan: { line1: "A real-company analogue generator", line2: "Your finance concept list plus current news headlines", line3: "Every concept gets a public-company example" },
    startupPitch: { name: "Boxcurve", tagline: "Powdered cheese, productized.", pitch: "AI optimizes neon-orange pigment delivery based on your tax-season anxiety. Synthetic cheddar is a regulated market; our moat is the FDA-yellow color spectrum." },
  },
  {
    stage: 'Curious', discipline: 'Entrepreneurship',
    teach: "Pre-write the email you've been avoiding, then ask AI to soften it",
    wish: "Take my messy founder interview notes and find the throughline",
    question: "How do I tell a 'good' AI demo from a polished hallucination?",
    build_idea: "A founder-interview throughline extractor",
    comfort_food: "Cinnamon raisin bagel with cream cheese",
    buildPlan: { line1: "An interview-throughline extractor", line2: "Three founder transcripts plus your research question", line3: "It names the unspoken pattern in under a minute" },
    startupPitch: { name: "Bagelseed", tagline: "Cinnamon-raisin, vertically integrated.", pitch: "Our AI calibrates cream cheese density to your Monday morning cortisol. We own the schmear-to-toast ratio category; the unit economics are deliciously asymmetric." },
  },
  {
    stage: 'Curious', discipline: 'Operations / Tech',
    teach: "Ask Claude to walk through your slide deck and find the missing diagram",
    wish: "Generate a working block diagram from my notes, not just a sketch",
    question: "Where do I draw the line between AI-augmented teaching and AI-replaced teaching?",
    build_idea: "A 'sketch to working diagram' helper for ops classes",
    comfort_food: "Spicy ramyun at midnight",
    buildPlan: { line1: "A sketch-to-diagram converter", line2: "Three of your hand-drawn process sketches", line3: "Students can read the digital version without you" },
    startupPitch: { name: "Spicechain", tagline: "Midnight ramyun, supply-side.", pitch: "AI-optimized Scoville delivery synced to your sleep debt. The umami moat is profound; we'll dominate the post-meeting noodle vertical by Q3." },
  },
  {
    stage: 'Curious', discipline: 'Marketing',
    teach: "Use AI to write three campaign concepts, then pick the most boring",
    wish: "Read student decks and tell me which one is genuinely a new idea",
    question: "What's the most over-rated AI use in marketing education right now?",
    build_idea: "A novelty scorer for student campaign concepts",
    comfort_food: "Buttery popcorn",
    buildPlan: { line1: "A novelty scorer for student campaigns", line2: "Ten last-term concepts plus a campaign database", line3: "Genuine novelty surfaces; recycled ideas don't" },
    startupPitch: { name: "Kerneldata", tagline: "Popcorn-driven attention metrics.", pitch: "AI matches butter saturation to your dopamine baseline before every movie. The moat is the corn-to-cuddle ratio. Investors are popping." },
  },
  {
    stage: 'Curious', discipline: 'Other',
    teach: "Ask AI for the version your skeptical colleague would actually read",
    wish: "Make my course intro sound less like every other course intro",
    question: "How do I make sure my course feels human in an AI-flooded year?",
    build_idea: "A 'not-like-every-other-course' rewriter for my syllabus intro",
    comfort_food: "Mint chocolate chip ice cream",
    buildPlan: { line1: "A syllabus-intro de-clichéifier", line2: "Your current intro plus three you wish you wrote", line3: "Students underline a real sentence on day one" },
    startupPitch: { name: "Mintly", tagline: "Toothpaste-aligned dessert.", pitch: "AI-balanced mint-to-chip ratios delivered via subscription. We're disrupting the freshness category; the dental-comfort moat is statistically delicious." },
  },
  {
    stage: 'Curious', discipline: 'Strategy / Management',
    teach: "Have AI list the assumptions baked into your strategy framework",
    wish: "Tell me which of my mental models are outdated for 2026",
    question: "Should I be teaching frameworks AI can apply, or judgment AI can't?",
    build_idea: "A framework-staleness auditor for my own lecture notes",
    comfort_food: "Dark chocolate with sea salt",
    buildPlan: { line1: "A framework-staleness auditor", line2: "Your lecture notes plus 2026 industry coverage", line3: "It flags the three frameworks you should retire" },
    startupPitch: { name: "Saltco", tagline: "Cocoa, but indexed.", pitch: "AI matches dark chocolate cacao percentage to your quarterly executive review. Saltflake density is our defensible moat. We're a category leader in bitterness." },
  },
  {
    stage: 'Curious', discipline: 'Entrepreneurship',
    teach: "Ask AI what your student's pitch is actually selling, not what they said",
    wish: "Spot the founder who's just performing competence",
    question: "How do I help students distinguish AI-mimicry of insight from real insight?",
    build_idea: "A 'performing vs knowing' detector for pitch decks",
    comfort_food: "Sourdough with good butter",
    buildPlan: { line1: "A pitch-deck performance detector", line2: "Five recorded pitches plus your own scoring rubric", line3: "Students see when polish is masking confusion" },
    startupPitch: { name: "Crustly", tagline: "Sourdough, but it ferments your TAM.", pitch: "AI-tuned crumb structure based on your founder's Hinge profile. The yeast moat is microbial. We're disrupting the bread-to-self-worth supply chain." },
  },
  {
    stage: 'Curious', discipline: 'Finance / Accounting',
    teach: "Get AI to compare two analyst reports side-by-side and find the lie",
    wish: "Catch which student copied last year's financial model and renamed it",
    question: "Will AI grading actually be more consistent than human grading in my field?",
    build_idea: "A 'last year's model' detector for student spreadsheets",
    comfort_food: "Hot chocolate with marshmallows",
    buildPlan: { line1: "A student-model plagiarism detector", line2: "Three years of submitted models plus your current crop", line3: "Copies surface; original work is left clean" },
    startupPitch: { name: "Mallowops", tagline: "Cocoa-as-a-Service.", pitch: "AI predicts how many marshmallows your portfolio needs before each board call. We own the molten-comfort vertical. Series A funded in mug-equivalents." },
  },
  {
    stage: 'Curious', discipline: 'Entrepreneurship',
    teach: "Ask AI to roast your business model canvas before showing it to students",
    wish: "Tell me when my hypothetical numbers don't add up before the class does",
    question: "Where should AI sit during a student-led case discussion?",
    build_idea: "A 'do my made-up numbers cohere' sanity check",
    comfort_food: "French fries with malt vinegar",
    buildPlan: { line1: "A made-up-numbers sanity checker", line2: "Three of your case briefs plus their TAMs and assumptions", line3: "It flags the place the math quietly breaks" },
    startupPitch: { name: "Crispcurve", tagline: "Fries with margin compression.", pitch: "AI-tuned malt vinegar acidity based on your weekly faculty meeting count. The fry-to-fatigue ratio is a defensible moat. Crinkle-cut Series B incoming." },
  },
  {
    stage: 'Curious', discipline: 'Operations / Tech',
    teach: "Use AI to convert a confusing process flow into a story your students can follow",
    wish: "Take my live whiteboard and clean it up by the end of class",
    question: "Will live AI in class change attention dynamics in ways I'm not ready for?",
    build_idea: "A whiteboard-to-cleaned-notes pipeline",
    comfort_food: "Roti and dal",
    buildPlan: { line1: "A whiteboard-to-cleaned-notes pipeline", line2: "A whiteboard photo plus your shorthand glossary", line3: "Students see a clean version before they leave" },
    startupPitch: { name: "Dalmark", tagline: "Lentils, deconstructed.", pitch: "AI matches dal spice profiles to your post-tenure stress index. We own the legume comfort vertical. Roti rollout is on a venture-grade schedule." },
  },

  // ─── Tinkering (18) ───────────────────────────────────────────────────────
  {
    stage: 'Tinkering', discipline: 'Entrepreneurship',
    teach: "Build a Claude project per course so it remembers the running context",
    wish: "Auto-generate the next-class warm-up from this class's loose ends",
    question: "What's the smallest classroom-AI workflow that actually persists?",
    build_idea: "A next-class warm-up generator from today's loose threads",
    comfort_food: "Sushi takeout",
    buildPlan: { line1: "A next-class warm-up generator", line2: "Today's class notes plus your weekly arc", line3: "Tomorrow's opener writes itself, accurately" },
    startupPitch: { name: "Wasabit", tagline: "Sushi-grade attention spans.", pitch: "AI-aligned ginger-to-nigiri ratios timed to faculty senate meetings. Our moat is the soy-stress sympatico. We're a category-defining roll." },
  },
  {
    stage: 'Tinkering', discipline: 'Marketing',
    teach: "Maintain a 'brand voice' Claude Project that quotes your three favorite agencies",
    wish: "Auto-grade campaign briefs with my exact rubric in my exact voice",
    question: "How do I keep my voice when AI is doing the first draft of everything?",
    build_idea: "A campaign-brief autograder in my voice",
    comfort_food: "Cheeseburger and fries",
    buildPlan: { line1: "A campaign-brief autograder in your voice", line2: "Your past comments plus your rubric", line3: "It feels like your handwriting on the page" },
    startupPitch: { name: "Pattymath", tagline: "Burgers as a brand.", pitch: "AI calibrates patty doneness to your campaign deadlines. The pickle-pickle moat is unfair. We're acquiring the medium-rare vertical by EOY." },
  },
  {
    stage: 'Tinkering', discipline: 'Entrepreneurship',
    teach: "Use Claude to outline a session, then have it self-critique against your goals",
    wish: "Plan a whole week of classes knowing my calendar and what I taught last year",
    question: "What's the workflow that finally got AI out of the 'demo' phase for you?",
    build_idea: "A week-planner that knows last year's syllabus",
    comfort_food: "Khao soi (chicken noodle curry soup)",
    buildPlan: { line1: "A week-planner with last year's memory", line2: "Last year's syllabus plus this year's calendar", line3: "Monday morning has a real plan before you sit down" },
    startupPitch: { name: "Soiware", tagline: "Curry-laced productivity.", pitch: "AI tunes coconut milk to chili ratio based on grading load. Our crispy-noodle topping is patented. We're the Toast-of-Thai of edtech." },
  },
  {
    stage: 'Tinkering', discipline: 'Strategy / Management',
    teach: "Drop your week's articles into NotebookLM and let it spot patterns",
    wish: "Generate a 'state of the discipline' brief once a month with no babysitting",
    question: "How do I keep current without burning Sundays on news?",
    build_idea: "A monthly discipline-state brief from my Readwise highlights",
    comfort_food: "Falafel pita",
    buildPlan: { line1: "A monthly state-of-discipline brief", line2: "Your Readwise feed plus three favorite journals", line3: "A two-page brief lands in your inbox" },
    startupPitch: { name: "Falafrm", tagline: "Pita-tracked discourse.", pitch: "AI fries chickpeas at the optimal temperature for Tuesday's department meeting. The tahini moat is creamy and defensible. Acquisitions pending." },
  },
  {
    stage: 'Tinkering', discipline: 'Finance / Accounting',
    teach: "Use Cowork to walk through a 10-K and write the teaching note for you",
    wish: "Translate a public 10-K into a case-quality teaching narrative",
    question: "What's the most under-rated AI tool you use weekly?",
    build_idea: "A 10-K to teaching-note translator",
    comfort_food: "Apple pie",
    buildPlan: { line1: "A 10-K-to-teaching-note translator", line2: "One company's 10-K plus your case-note template", line3: "A teachable narrative replaces 80 dry pages" },
    startupPitch: { name: "Crustdex", tagline: "Apple pie, indexed quarterly.", pitch: "AI matches cinnamon-to-streusel ratios based on tax-loss harvesting deadlines. We've defined the cobbler-comfort vertical. The lattice moat is structurally sound." },
  },
  {
    stage: 'Tinkering', discipline: 'Entrepreneurship',
    teach: "Build a case-brief Claude project that pulls in your news of the week",
    wish: "Spot the moment my class energy drops on Zoom and tell me why",
    question: "What's one workflow you'd hand a colleague tomorrow morning?",
    build_idea: "A class-energy monitor from the Zoom transcript",
    comfort_food: "Pierogi with sour cream",
    buildPlan: { line1: "A class-energy auditor", line2: "Your Zoom transcript plus an attention rubric", line3: "It names the minute the room dropped" },
    startupPitch: { name: "Doughpoint", tagline: "Pierogi, but with retention.", pitch: "AI-stuffed potato ratios calibrated to your team-meeting fatigue. We dominate the pinch-and-pleat vertical; the sour cream moat is profoundly tangy." },
  },
  {
    stage: 'Tinkering', discipline: 'Marketing',
    teach: "Use Claude Projects to keep your example brands current across the semester",
    wish: "Suggest a current campaign analogue for any chapter I'm teaching",
    question: "How do I update examples weekly without spending hours on it?",
    build_idea: "A current-campaign analogue generator for textbook chapters",
    comfort_food: "Donut and coffee",
    buildPlan: { line1: "A current-campaign analogue generator", line2: "Your chapter outline plus this month's news", line3: "Every concept gets a 2026 example" },
    startupPitch: { name: "Glazely", tagline: "Donuts, but for KPIs.", pitch: "AI-piped frosting depth modeled on Q3 revenue concerns. We own the carb-comfort vertical. The maple-bacon TAM expanded 14% this fiscal." },
  },
  {
    stage: 'Tinkering', discipline: 'Operations / Tech',
    teach: "Have Claude Cowork read a process doc and propose the missing edge cases",
    wish: "Find the bug in my student's code without writing the fix for them",
    question: "How do I let AI help students debug without doing the debug?",
    build_idea: "A Socratic-debugger that asks instead of fixing",
    comfort_food: "Bibimbap with extra gochujang",
    buildPlan: { line1: "A Socratic code-debugger", line2: "A broken student notebook plus your hint hierarchy", line3: "Students fix it themselves, with smaller hints" },
    startupPitch: { name: "Bowlchain", tagline: "Bibimbap, but it scales.", pitch: "AI mixes gochujang ratios based on your sprint retro outcomes. We're disrupting the rice-bowl supply graph. The crispy-bottom moat is fundamentally crunchy." },
  },
  {
    stage: 'Tinkering', discipline: 'Entrepreneurship',
    teach: "Use AI to draft your peer feedback notes within 24 hours of class",
    wish: "Read all twenty student journals and surface the three I should worry about",
    question: "When does saving time with AI start to cost me what I notice as a teacher?",
    build_idea: "A pastoral-care surface from student reflection journals",
    comfort_food: "Tandoori chicken and naan",
    buildPlan: { line1: "A reflection-journal triage", line2: "Twenty student journals plus your concern list", line3: "Three flags surface; the rest stay private" },
    startupPitch: { name: "Tandurly", tagline: "Naan-fungible alpha.", pitch: "AI calibrates marinade overnight intervals to your sabbatical countdown. The clay-oven thermal moat is defensible. We've owned the chicken-and-confidence vertical since 2024." },
  },
  {
    stage: 'Tinkering', discipline: 'Finance / Accounting',
    teach: "Use AI to walk through your spreadsheet logic aloud before students see it",
    wish: "Auto-build a teaching version of any company's model with sensible dummy data",
    question: "How do I teach valuation when AI builds the model in twenty seconds?",
    build_idea: "A 'teaching version' generator for finance models",
    comfort_food: "Banana bread",
    buildPlan: { line1: "A teaching-model generator", line2: "One real DCF plus your simplification rules", line3: "Students get a clean classroom version, instantly" },
    startupPitch: { name: "Loafledger", tagline: "Banana bread on the balance sheet.", pitch: "AI matches ripeness curves to your tax-quarter dread. Our overripe-banana moat is unbeatable; we're the only player vertically integrated from peel to slice." },
  },
  {
    stage: 'Tinkering', discipline: 'Strategy / Management',
    teach: "Drop your case files into Cowork and have it find your blind spots",
    wish: "Identify the unstated assumption in any case before I teach it",
    question: "What does 'AI-fluent strategy professor' actually mean in 2026?",
    build_idea: "An unstated-assumption finder for case files",
    comfort_food: "Tortellini in brodo",
    buildPlan: { line1: "An unstated-assumption finder", line2: "Three favorite case PDFs plus your discussion plan", line3: "It names the assumption you never check" },
    startupPitch: { name: "Brothbase", tagline: "Tortellini-as-a-Service.", pitch: "AI-shaped pasta optimized for executive cohort indigestion. The parmesan-rind moat is unfair. We've subscription-pivoted the Italian-grandma vertical." },
  },
  {
    stage: 'Tinkering', discipline: 'Entrepreneurship',
    teach: "Run your VC class with Cowork as a third-chair analyst",
    wish: "Critique my student's data room like a Series A partner would",
    question: "How do I prepare students for VC interviews when AI is also in the room?",
    build_idea: "A Series-A-partner-grade data-room critic",
    comfort_food: "Tres leches cake",
    buildPlan: { line1: "A Series-A data-room critic", line2: "One student data room plus three real partner notes", line3: "Students see the partner's three follow-ups before the meeting" },
    startupPitch: { name: "Lechecorp", tagline: "Cakes that compound quarterly.", pitch: "AI predicts which of the three milks resolves your investor anxiety fastest. We're the moat in moisture; the cake-to-clarity unit economics are deliciously asymmetric." },
  },
  {
    stage: 'Tinkering', discipline: 'Marketing',
    teach: "Use AI as your fact-checker before you let a student insight onto a slide",
    wish: "Verify every brand fact in my deck without me retracing each citation",
    question: "How do I make sure my class doesn't drift into AI-sounding mush?",
    build_idea: "A brand-fact verifier for slide decks",
    comfort_food: "Buttery shortbread",
    buildPlan: { line1: "A brand-fact verifier for slides", line2: "Your deck plus your top-three trusted sources", line3: "Every claim points to a citation" },
    startupPitch: { name: "Shortlit", tagline: "Shortbread, but liquid.", pitch: "AI-buttered cookies tuned to your post-tenure restlessness. We dominate the crumble-comfort vertical; the dough-density moat is statistically golden." },
  },
  {
    stage: 'Tinkering', discipline: 'Other',
    teach: "Build a Claude project per advisee and have it surface what's drifting",
    wish: "Watch all my advisees' weeks and tell me who's quietly stuck",
    question: "What's an AI use case you abandoned because it didn't fit how you teach?",
    build_idea: "A 'quietly stuck advisee' detector",
    comfort_food: "Onigiri with salmon",
    buildPlan: { line1: "A quietly-stuck advisee detector", line2: "Three advisees' weekly updates plus your concern signals", line3: "The one you should call surfaces this week" },
    startupPitch: { name: "Onigirly", tagline: "Rice balls with retention guarantees.", pitch: "AI maps nori-to-rice ratios against your office-hour load. The triangular form factor is our moat. We've cornered the bento subscription category." },
  },
  {
    stage: 'Tinkering', discipline: 'Operations / Tech',
    teach: "Use Cowork to translate a vendor diagram into a teaching-friendly version",
    wish: "Take any vendor whitepaper and pull the actually-novel claim",
    question: "What's an AI use case I should retire because it never actually worked?",
    build_idea: "A novelty-extractor for vendor whitepapers",
    comfort_food: "Tom kha soup",
    buildPlan: { line1: "A whitepaper novelty extractor", line2: "Five vendor PDFs plus your skeptic's question list", line3: "Three real claims surface; the rest get cut" },
    startupPitch: { name: "Khazoom", tagline: "Coconut broth, fully managed.", pitch: "AI tunes galangal-to-lemongrass ratios using your last sprint retro. Our umami moat is creamily defensible. Series B sourced via Bangkok markets." },
  },
  {
    stage: 'Tinkering', discipline: 'Finance / Accounting',
    teach: "Have AI draft three teaching cases from one earnings call",
    wish: "Pre-write the dumb questions students should be allowed to ask without judgment",
    question: "How do I teach financial humility when AI never seems unsure?",
    build_idea: "A 'safe-to-ask' question library for finance",
    comfort_food: "Pumpkin pie",
    buildPlan: { line1: "A safe-to-ask question library", line2: "Your three hardest chapters plus past student emails", line3: "Students walk in with a smaller knot" },
    startupPitch: { name: "Pielogic", tagline: "Pumpkin pie, but for treasury.", pitch: "AI spices your crust to match year-end audit fatigue. We've categorically defined the gourd-comfort vertical. The whipped-cream moat is fluffy and unfair." },
  },
  {
    stage: 'Tinkering', discipline: 'Entrepreneurship',
    teach: "Use Claude to turn your founder Q&A transcripts into discussion prompts",
    wish: "Generate next semester's startup brief library from this term's class threads",
    question: "How do I scale my own teaching style without scaling my own hours?",
    build_idea: "A semester-to-brief library generator",
    comfort_food: "Late-night nachos",
    buildPlan: { line1: "A semester-to-brief library generator", line2: "This term's class threads plus your brief template", line3: "Next semester's reading pack is ready by finals week" },
    startupPitch: { name: "Nachoscope", tagline: "Tortilla chips, indexed.", pitch: "AI matches jalapeño density to your end-of-quarter exhaustion. The melted-cheese moat is bubbling and unrivaled. Pre-seed rounds served with sour cream." },
  },
  {
    stage: 'Tinkering', discipline: 'Strategy / Management',
    teach: "Use AI to track which of your examples land and which don't",
    wish: "Score every analogy I use against student exam-question performance",
    question: "What's the AI-teaching insight you keep coming back to a year later?",
    build_idea: "An analogy-landing scorer from exam data",
    comfort_food: "Latte and a croissant",
    buildPlan: { line1: "An analogy-landing scorer", line2: "Your past exam answers plus the analogies you used in class", line3: "It names the three analogies actually doing work" },
    startupPitch: { name: "Crissup", tagline: "Croissants with KPIs.", pitch: "AI laminates butter ratios timed to your weekly executive briefings. The flake-density moat is statistically buttery. Series A coming in Paris-only cohorts." },
  },

  // ─── Builders (10) ────────────────────────────────────────────────────────
  {
    stage: 'Building', discipline: 'Entrepreneurship',
    teach: "Wire your case-prep flow into a Claude project that pulls news daily",
    wish: "Spin up a course-aware AI TA my students can actually trust at 11pm",
    question: "How do I build trust in an AI TA without giving up oversight?",
    build_idea: "A course-aware AI TA my students can use at 11pm",
    comfort_food: "Salmon teriyaki bowl",
    buildPlan: { line1: "A course-aware AI TA prototype", line2: "Your syllabus, three lectures, and your FAQ", line3: "It answers the 11pm question the way you would" },
    startupPitch: { name: "Tériyak", tagline: "Salmon teriyaki, vertically integrated.", pitch: "AI matches glaze viscosity to your tenure-review milestone. The seared-skin moat is crispy and venture-grade. We're the only player in the bowl-to-meaning category." },
  },
  {
    stage: 'Building', discipline: 'Entrepreneurship',
    teach: "Run your venture studio on a shared Claude project with three founders",
    wish: "Auto-generate a pitch-readiness scorecard from any deck I'm sent",
    question: "How do I scale venture-studio mentorship without losing what makes it personal?",
    build_idea: "A pitch-readiness scorer used inside my venture studio",
    comfort_food: "Sashimi platter",
    buildPlan: { line1: "A pitch-readiness scorer for your studio", line2: "Five recent decks plus your partner scorecard", line3: "Founders see what's still missing before the meeting" },
    startupPitch: { name: "Sashiware", tagline: "Sashimi as a managed service.", pitch: "AI grades tuna belly fat content against your investor pipeline volatility. The wasabi-burn moat is sharp and uncopiable. Pre-seed served with hot towels." },
  },
  {
    stage: 'Building', discipline: 'Marketing',
    teach: "Build a per-course Claude project that grades briefs in your house style",
    wish: "Auto-build a personalized marketing portfolio for each student by graduation",
    question: "Will personalized AI portfolios replace internships or amplify them?",
    build_idea: "A student-portfolio generator from semester work",
    comfort_food: "Crème brûlée",
    buildPlan: { line1: "A student-portfolio generator", line2: "Their semester's work plus your portfolio criteria", line3: "Each student leaves with a real, shareable site" },
    startupPitch: { name: "Caramella", tagline: "Crème brûlée meets KPIs.", pitch: "AI calibrates torch heat to your acceptance-letter anxiety. The sugar-crackle moat is sharply audible. Subscription tiers unlock additional spoons." },
  },
  {
    stage: 'Building', discipline: 'Operations / Tech',
    teach: "Wire Cowork into your office hours via a shared folder of office notes",
    wish: "Run a course-wide AI co-pilot that knows my office hours and tone",
    question: "How do I make AI in the loop without making it feel like surveillance?",
    build_idea: "A course-wide office-hours co-pilot with my tone",
    comfort_food: "Hot pot with friends",
    buildPlan: { line1: "An office-hours co-pilot with your tone", line2: "Three months of your office-hours notes plus your style samples", line3: "Students recognize you in the responses" },
    startupPitch: { name: "Potlogic", tagline: "Hot pot, but provisioned.", pitch: "AI matches broth temperature to your weekly faculty conflict index. The dipping-sauce moat is creamy-sesame. We're disrupting the communal-meal supply chain." },
  },
  {
    stage: 'Building', discipline: 'Strategy / Management',
    teach: "Run a Cowork project across every case in your course, not just one",
    wish: "Generate term-long arcs of cases that build on each other automatically",
    question: "Are AI-built case arcs going to redefine how strategy is taught?",
    build_idea: "A term-long case-arc generator",
    comfort_food: "Khachapuri",
    buildPlan: { line1: "A term-long case-arc generator", line2: "Your past case library plus your learning-objective tree", line3: "Each case sets up the next without you re-sequencing" },
    startupPitch: { name: "Puriline", tagline: "Bread boats with shipping containers.", pitch: "AI-melted suluguni ratios tuned to your geopolitical seminar load. The egg-yolk-on-top moat is unmatched. Series A backed by Tbilisi seed funds." },
  },
  {
    stage: 'Building', discipline: 'Entrepreneurship',
    teach: "Build a course Cowork project, then let students contribute artifacts back",
    wish: "Have every assignment compound into a portfolio of teaching material",
    question: "How do I turn student work into next year's curriculum without exploiting them?",
    build_idea: "A student-work-to-curriculum pipeline (with consent)",
    comfort_food: "Empanadas",
    buildPlan: { line1: "A consent-first curriculum pipeline", line2: "This term's strongest student artifacts plus your reuse policy", line3: "Next year's curriculum cites this year's students" },
    startupPitch: { name: "Empandalytics", tagline: "Empanadas with provenance.", pitch: "AI-folded dough patterns matched to your sabbatical eligibility. The chimichurri moat is bright and verdant. Distribution? Hot, by Tuesday." },
  },
  {
    stage: 'Building', discipline: 'Finance / Accounting',
    teach: "Build a Claude project per industry sector you teach, with live filings",
    wish: "Build a live, sector-aware case library that updates each quarter",
    question: "What's the right way to teach financial judgment when models are commoditized?",
    build_idea: "A self-updating, sector-aware case library",
    comfort_food: "Truffle fries",
    buildPlan: { line1: "A self-updating sector case library", line2: "Three sector watchlists plus your case template", line3: "Quarterly updates land without you sourcing each one" },
    startupPitch: { name: "Trufflinks", tagline: "Truffle fries, securitized.", pitch: "AI matches truffle oil to your earnings-call season. The waffle-cut moat is geometrically defensible. We're the only player at the intersection of starch and prestige." },
  },
  {
    stage: 'Building', discipline: 'Entrepreneurship',
    teach: "Run your community-coach office hours with Cowork in the loop",
    wish: "Coach a hundred founders at once without losing the human bit",
    question: "Where's the human seam I want to keep visible in my work?",
    build_idea: "A founder-coaching co-pilot that knows my whole portfolio",
    comfort_food: "Halal cart chicken over rice",
    buildPlan: { line1: "A founder-coaching co-pilot", line2: "Your portfolio's notes plus your coaching framework", line3: "Each founder gets a tailored prep doc before each session" },
    startupPitch: { name: "Halalysis", tagline: "Chicken over rice, but enterprise.", pitch: "AI-balanced white-sauce-to-hot-sauce ratios tuned to your cohort's velocity metrics. The midtown-corner moat is real estate-grade. Lunch IPO incoming." },
  },
  {
    stage: 'Building', discipline: 'Other',
    teach: "Use Claude to keep a 'what worked' journal across your courses",
    wish: "Stitch together a multi-year teaching practice journal from all my notes",
    question: "How do I distill 15 years of teaching into something AI can actually keep alive?",
    build_idea: "A multi-year teaching-practice journal stitcher",
    comfort_food: "Borscht and rye bread",
    buildPlan: { line1: "A multi-year teaching journal stitcher", line2: "Fifteen years of class notes plus your retro template", line3: "A pattern emerges that you've never written down" },
    startupPitch: { name: "Borschtly", tagline: "Beets with longitudinal data.", pitch: "AI matches sour cream swirl patterns to your administrative review cycle. The dill moat is herbal and statistically significant. Subscription served warm." },
  },
  {
    stage: 'Building', discipline: 'Marketing',
    teach: "Build a brand-voice critic per brand you cover, refreshed every quarter",
    wish: "Generate a working campaign every Friday based on the week's news for student practice",
    question: "How do I make the practice problems feel as real as the actual industry?",
    build_idea: "A weekly news-to-campaign practice generator",
    comfort_food: "Chocolate babka",
    buildPlan: { line1: "A weekly campaign-practice generator", line2: "This week's headlines plus your client brief format", line3: "Students arrive Monday with a real-world prompt waiting" },
    startupPitch: { name: "Babkalogy", tagline: "Chocolate babka, but for cohorts.", pitch: "AI-swirled cocoa loaves tuned to your faculty meeting density. The braided-dough moat is structurally undeniable. Series A in proof-of-laminate." },
  },
];
